### ISSUE TITLE
Can lwc css import Static Resource css?

### ISSUE THREAD

**Issue by KelvinHuangDZ** [albarivas/shadow-dom#1]
Hi, I got a question is there a way my lwc css import a Static Resource css?
I have a lwc that is both available in the sf community and sf record page. I have build all my community custom css and saved all in the Static Resource. When I drop this lwc into the sf record page, I wish to apply the custom css to this component only. I have tried to use loadStyle in the js, as your video mentioned it's apply the css to the Global level. Is there a way this lwc css can ref to the custom css in the Static Resource?

**Comment by navkn** [comment]
As per their presentation , we can load static resource into the particular lwc's css file and you can watch that at  https://www.youtube.com/watch?v=T7OGDMRnjT4 and the timeline is **45:00** .

**Comment by albarivas** [comment]
Sorry for the late reply. Yes, so you have two options really:

- Load your styles using a static resource --> they're loaded globally and may modify other components on the page unexpectedly
- Enclose your styles in a CSS module and load it with @import --> they'll be scoped to your component. I recommend you to follow this approach if possible.

Cheers, and thank you @navkn for helping too.

**Comment by KelvinHuangDZ** [comment]
> As per their presentation , we can load static resource into the particular lwc's css file and you can watch that at https://www.youtube.com/watch?v=T7OGDMRnjT4 and the timeline is **45:00** .

Hi Navkn, i want to use cmp css module imported using @import to import css file from Static Resource.
I tried: 
@import url('/resource/xxx/main.css')
or
@import url('@salesforce/resource/xxx/main.css');
Getting invalid import statement, unable to find imported module.

**Comment by albarivas** [comment]
You cannot do that. You have to move your CSS into a component that just contains a CSS file. And then @import it, like this https://github.com/albarivas/shadow-dom/blob/master/force-app/main/default/lwc/importCSSsharedModule/importCSSsharedModule.css

**Comment by KelvinHuangDZ** [comment]
Is there anywhere we can requested this feature? This should be standard css rules
https://developer.mozilla.org/en-US/docs/Web/CSS/@import

**Comment by albarivas** [comment]
You can try to log it in https://github.com/salesforce/lwc
